# [START django_app]
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static/
- url: .*
  static_dir: main.application

  libraries:

    name: django
    version:"1.11"

    env_nariables:
      DJANGO_SETTINGS_MODULE:'hotelreviews.settings'